name: Generate ASCII Artwork using script

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Executing shell script
        run: ./ascii-art.sh
