name: Multiple jobs example

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay program
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON! ... RAWR" >> dragon.txt

      - name: Sleep for 2 seconds
        run: sleep 2

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v3
        with:
          name: dragon-text-file # unique name that can be anything and we can use the name to download the artifact later
          path: dragon.txt

  test_job:
    needs: build_job # this job will run after build_job is successfully completed
    runs-on: ubuntu-latest
    steps:
      - name: Downlaod Dragon text file
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file
      - name: Test file exits
        run: grep -i "dragon" dragon.txt

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Downlaod Dragon text file
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file
      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying the application with the generated ASCII art ........."
